[theme]
base="light"
primaryColor="#1f77b4"
backgroundColor="#FFFFF0"
secondaryBackgroundColor="#F5F5F5"
textColor="#000000"
font="sans serif"


[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
headless = true
enableCORS = true
maxUploadSize = 200
